[project]
name = "starterpack-retail-banking-en"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "rasa-pro>=3.13.0",
]
