recipe: default.v1
language: en
assistant_id: banking-assistant

pipeline:
- name: CompactLLMCommandGenerator
  llm:
    model_group: openai-direct-gpt-4o
  prompt_template: prompts/command-generator.jinja2

policies:
- name: FlowPolicy
- name: EnterpriseSearchPolicy
  model: gpt-4o-mini
  vector_store:
    type: "faiss"
    source: "./docs"
